# After registering a name on build.snapcraft.io, commit an uncommented line:
name: md5-console
version: '0.01.20220424' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple tool for calculating MD5. # 79 char long summary
description: |
  A simple tool for calculating MD5, created by Joker2770< https://github.com/Joker2770/md5-console >.

# icon: gui/icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

apps:
  md5-console:
    command: usr/local/bin/md5-console
      
parts:
  md5-console:
    # See 'snapcraft plugins'
    plugin: cmake
    source: "https://github.com/Joker2770/md5.git"
    # source: ../
    source-depth: 1
    source-branch: main
    source-type: git
    build-packages:
     - gcc
     - g++
     - cmake
     - make
     
