#    A simple tool for calculating MD5. 
#    Copyright (C) 2022  joker2770
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: md5-console
version: '0.02.20220424' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple tool for calculating MD5. # 79 char long summary
description: |
  A simple tool for calculating MD5, created by Joker2770< https://github.com/Joker2770/md5-console >.

# icon: gui/icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
license: 'GPL-2.0+'

apps:
  md5-console:
    command: usr/local/bin/md5
    plugs:
      - home
      - removable-media
      
parts:
  md5-console:
    # See 'snapcraft plugins'
    plugin: cmake
    source: "https://github.com/Joker2770/md5.git"
    # source: ../
    source-depth: 1
    source-branch: main
    source-type: git
    build-packages:
     - gcc
     - g++
     - cmake
     - make
     
